import type { Coords, Severity, StationKind } from '../../shared/contracts'
import { STATION_SEEDS } from './stations'

export interface DispatchSeed {
  stationCode: string
  title: string
  body: string
  severity: Severity
  tags: string[]
  hoursAgo: number
  filedBy: string
  coords: { lat: number; lng: number } | null
}

export interface WireTemplate {
  title: string
  body: string
  severity: Severity
  tags: string[]
  kinds?: StationKind[]
}

/** Operators rotate between stations; the store draws from this list for wire traffic. */
export const OPERATOR_CALLSIGNS: string[] = [
  'Wren-6',
  'Mace-2',
  'Halloran',
  'Teague-3',
  'Orsk',
  'Brindle',
  'Kestrel-9',
  'Lomax',
  'Sable-4',
  'Ptarmigan',
  'Ingram',
  'Dunlin-1',
]

/** A point a short walk from the named station, rounded to the precision a handheld receiver reports. */
function near(code: string, dLat: number, dLng: number): Coords {
  const s = STATION_SEEDS.find((x) => x.code === code)
  if (!s) throw new Error(`Unknown station code in dispatch seed: ${code}`)
  return { lat: Number((s.lat + dLat).toFixed(4)), lng: Number((s.lng + dLng).toFixed(4)) }
}

/**
 * 64 dispatches, written oldest first. The storylines that run across days:
 *  - RVN-01 generator A: third-pull habit, failure, fuel request, slipped flight, fix.
 *  - KRN-07 sea ice: first lead to open water, with one bad afternoon in the middle.
 *  - TLV-04 mast icing: rime, loading, partial clear, a wet connector.
 *  - ULG-06 missed scheduled contacts, then recovery.
 *  - SKR-11 crevasse fall and what it does to the roster at BRD-08.
 *  - BRD-08 small-event swarm.
 *  - HLV-02 cracked anemometer cup, and an overdue walker.
 *  - VLD-13 gale, buried array, load shedding, silence. Not resolved.
 */
export const DISPATCH_SEEDS: DispatchSeed[] = [
  {
    stationCode: 'ULG-06',
    title: 'Handover taken, ledger counted',
    body: 'Took the station from the outgoing crew at 1015 local. Ledger complete to the last page; the last entry is a recipe for flatbread and I have left it there. Keys: four, expected five. The fifth was on the hook in the generator shed, which is where everyone but the previous crew would have looked. Fuel 340 L, rations for 41 days at three persons.',
    severity: 'routine',
    tags: ['handover', 'logistics'],
    hoursAgo: 478,
    filedBy: 'Dunlin-1',
    coords: null,
  },
  {
    stationCode: 'RVN-01',
    title: 'Arctic fox count, north cairn',
    body: 'Two adult foxes at the north cairn at 0640, a third at 0655 that did not stay. One has a notched left ear and is logged as Notch. They took a glove off the drying line and buried it beside the survey marker. Glove recovered at 0900, somewhat improved by the experience.',
    severity: 'routine',
    tags: ['wildlife', 'survey'],
    hoursAgo: 466,
    filedBy: 'Ptarmigan',
    coords: near('RVN-01', 0.0031, -0.0112),
  },
  {
    stationCode: 'KRN-07',
    title: 'Barograph pen and chart drum',
    body: 'Fitted a new pen nib and wound a fresh weekly chart. The drum runs four minutes fast per week, which is within what the handbook tolerates and within what the drum has always done. Trace since Tuesday holds near 1009 hPa with one dip of 3 hPa on Thursday night. Nothing followed the dip.',
    severity: 'routine',
    tags: ['instrument', 'maintenance'],
    hoursAgo: 452,
    filedBy: 'Wren-6',
    coords: near('KRN-07', 0.0002, 0.0003),
  },
  {
    stationCode: 'BRD-08',
    title: 'Vault temperature steady at 2.1 C',
    body: 'Vault temperature 2.1 C, variation under 0.05 C across the week. Seismometer mass centred; no adjustment needed since the 14th. Microseism peak in the 0.1 to 0.3 Hz band reads 41 dB, ordinary for the season. Door seal greased. The hut stove draws hard in a north wind, noted for whoever sleeps nearest it.',
    severity: 'routine',
    tags: ['seismic', 'instrument'],
    hoursAgo: 441,
    filedBy: 'Brindle',
    coords: null,
  },
  {
    stationCode: 'OST-09',
    title: 'Stilling well silted, trace flat-topped',
    body: 'The gauge trace has been flat at high water since Sunday, which the tide is not. Probed the intake from the quay at low water: 18 cm of silt packed against the screen. Cleared by rake and by hand in two hours. Trace normal again from the 1640 tide. Intake check every ten days until the storm season closes.',
    severity: 'notice',
    tags: ['instrument', 'maintenance'],
    hoursAgo: 430,
    filedBy: 'Mace-2',
    coords: near('OST-09', -0.0004, 0.0009),
  },
  {
    stationCode: 'SKR-11',
    title: 'Line C stake readings',
    body: 'Ablation stakes on line C, read at 1100. C1 down 0.42 m since the last reading. C2 0.38 m. C3 0.51 m. C4 0.47 m. C5 not found; melted out, stake and all. Spare stake drilled in 6 m uphill of the old site and flagged with orange tape. Surface is wet slush over hard ice above C3 and walkable in crampons only.',
    severity: 'routine',
    tags: ['ice', 'survey'],
    hoursAgo: 418,
    filedBy: 'Orsk',
    coords: near('SKR-11', 0.0062, 0.0141),
  },
  {
    stationCode: 'GLM-12',
    title: 'Hut guys re-tensioned, relay nominal',
    body: 'Re-tensioned the four guy cables after the last blow; two had slackened by 15 mm. Forward power 12 W, reflected 0.4 W. Passed 38 messages in the evening window, none repeated.',
    severity: 'routine',
    tags: ['comms', 'maintenance'],
    hoursAgo: 402,
    filedBy: 'Lomax',
    coords: near('GLM-12', 0.0002, 0.0005),
  },
  {
    stationCode: 'HLV-02',
    title: 'Anemometer cup cracked',
    body: 'One of the three cups on the main anemometer is split along the seam, found at the 0800 round. The rotor still turns but has begun to wobble. Taped the crack as a holding measure. Replacement requested from the store. The tape is not a repair and is not recorded as one.',
    severity: 'notice',
    tags: ['instrument'],
    hoursAgo: 388,
    filedBy: 'Halloran',
    coords: near('HLV-02', 0.0008, 0.0021),
  },
  {
    stationCode: 'TLV-04',
    title: 'Aurora noise on the plateau link',
    body: 'Noise floor on the 4.6 MHz channel rose from -112 to -101 dBm between 2240 and 0130 under a bright band in the north. Moved traffic to 6.2 MHz and throughput recovered. Back on the primary at 0210 when the noise dropped. The other forty minutes of the watch were spent outside, which is also logged.',
    severity: 'routine',
    tags: ['aurora', 'comms'],
    hoursAgo: 366,
    filedBy: 'Kestrel-9',
    coords: null,
  },
  {
    stationCode: 'HLV-02',
    title: 'Main anemometer reads 18 percent low',
    body: 'Six hours of comparison against the handheld at the mast. Handheld 14.0 m/s, main 11.5 m/s, steady across the run. The taped cup has lost enough of its scoop to matter. All main-anemometer values from the 4th onward are flagged suspect. Primary switched to the backup vane, which tops out at 25 m/s.',
    severity: 'notice',
    tags: ['instrument', 'maintenance'],
    hoursAgo: 340,
    filedBy: 'Teague-3',
    coords: null,
  },
  {
    stationCode: 'SKR-11',
    title: 'Fall into crevasse on line D',
    body: '1402. Brindle broke through a snow bridge at D4 on the way to the far stake. Roped to Orsk, held at 2 m, then dropped to about 6 m when the lip gave. Voice contact throughout. Out at 1437 on the pulley system, 35 minutes in all. Conscious, cold, complaining of the left ribs. Conscious and talking is the whole of the status so far.',
    severity: 'critical',
    tags: ['medical', 'ice'],
    hoursAgo: 336,
    filedBy: 'Orsk',
    coords: near('SKR-11', 0.0108, 0.0226),
  },
  {
    stationCode: 'SKR-11',
    title: 'Casualty stable, evacuation flight offered',
    body: 'Brindle in the hut since 1530, dry clothes, stove on full. Pulse 88, respiration 18, pain on deep breath, left lower ribs tender, no blood, no head strike. The flight operator has offered a slot at first light if the ceiling holds above 300 m. Brindle declines evacuation for now and Orsk has logged that he declined. Reassess at 0600.',
    severity: 'urgent',
    tags: ['medical', 'logistics'],
    hoursAgo: 334,
    filedBy: 'Orsk',
    coords: null,
  },
  {
    stationCode: 'SKR-11',
    title: 'Brindle to Bredon for desk duty',
    body: 'Reassessed at 0600 and again at 1200. Breathing is easier, the ribs are not. Medical advice by radio: no hauling and no ropes for three weeks. Brindle goes to Bredon on the next flight and takes the seismic desk, which needs one person who sits down. Orsk holds Skarra with the contractor until a relief is named. Line D stays closed; the bridge at D4 is marked with two bamboo crosses.',
    severity: 'notice',
    tags: ['medical', 'handover'],
    hoursAgo: 322,
    filedBy: 'Orsk',
    coords: null,
  },
  {
    stationCode: 'RVN-01',
    title: 'Generator A starts on the third pull again',
    body: 'Generator A, cold, outside -18 C. First pull: nothing. Second pull: a cough. Third pull: runs. Eleventh morning in a row. Logged as a habit and not a fault, so that nobody calls it a surprise later. Load 4.1 kW, fuel 512 L across the day tank and drums.',
    severity: 'routine',
    tags: ['power', 'maintenance'],
    hoursAgo: 312,
    filedBy: 'Ingram',
    coords: near('RVN-01', 0.0004, -0.0006),
  },
  {
    stationCode: 'VLD-13',
    title: 'Weekly event catalogue',
    body: 'Local events this week: 14, magnitudes 0.2 to 1.6, all within 30 km. Nothing felt. Largest at 0312 on the 19th, depth 6 km, clean on all three components. Logger clock drifted 0.3 s against the GPS pulse and has been corrected. Disk 61 percent.',
    severity: 'routine',
    tags: ['seismic', 'survey'],
    hoursAgo: 296,
    filedBy: 'Sable-4',
    coords: near('VLD-13', 0.0002, -0.0003),
  },
  {
    stationCode: 'OST-09',
    title: 'Stove pipe swept, damper replaced',
    body: 'Swept the pipe and replaced the damper plate. The old one came out in two pieces. Draw is better and the room is now 4 degrees too warm, so there is a new problem. Quay lamp bulb replaced; it outlived the last one, which lasted nine days.',
    severity: 'routine',
    tags: ['maintenance'],
    hoursAgo: 280,
    filedBy: 'Mace-2',
    coords: near('OST-09', -0.0003, 0.0006),
  },
  {
    stationCode: 'RVN-01',
    title: 'Generator A will not start',
    body: 'Fifteen pulls between 0630 and 0700. Fuel reaches the carburettor; no spark at the plug on inspection. Generator B took the load at 0712 and is carrying 4.4 kW against a 6 kW rating. No redundancy until A is fixed. Day tank 388 L, burn about 41 L a day. Spare plug fitted to A and still no spark, so the coil is suspect.',
    severity: 'urgent',
    tags: ['power'],
    hoursAgo: 270,
    filedBy: 'Ingram',
    coords: near('RVN-01', 0.0004, -0.0006),
  },
  {
    stationCode: 'RVN-01',
    title: 'Fuel and ignition coil requested',
    body: 'Request for the next flight: 600 L diesel in drums, one ignition coil for Generator A, one plug set. Ptarmigan puts the fuel at nine days at the current burn, eleven if the galley stops running the second heater. The second heater was put to a vote. The vote was close.',
    severity: 'notice',
    tags: ['supply', 'logistics', 'power'],
    hoursAgo: 268,
    filedBy: 'Ptarmigan',
    coords: null,
  },
  {
    stationCode: 'BRD-08',
    title: 'Small events clustering north of the nunatak',
    body: 'Six events between 0140 and 0500 within 12 km of the station, magnitudes 0.4 to 1.1. The normal rate for that box is about one a day. Epicentres line up east to west at 4 to 7 km depth. No felt reports. Logger at 200 samples per second and triggering as intended. Mass position checked every watch.',
    severity: 'notice',
    tags: ['seismic'],
    hoursAgo: 252,
    filedBy: 'Brindle',
    coords: near('BRD-08', 0.071, 0.012),
  },
  {
    stationCode: 'BRD-08',
    title: 'Cluster rate at 40 events an hour',
    body: 'Between 1900 and 2000 the logger counted 41 events, largest M 2.3, located 8 km north-northwest at 5 km depth. Hut windows rattled at 1954 and the kettle moved a centimetre on the stove. Reported to the regional seismic desk at 2012; they gave reference 4471 and acknowledged. Crew sleeping in boots. Mass re-centred twice.',
    severity: 'urgent',
    tags: ['seismic', 'comms'],
    hoursAgo: 240,
    filedBy: 'Brindle',
    coords: near('BRD-08', 0.074, -0.011),
  },
  {
    stationCode: 'RVN-01',
    title: 'Supply flight slipped one day',
    body: "Tuesday's flight is now Wednesday. Reason from the operator: crosswind at the departure strip, gusting 48 km/h. Our strip has 12 km/h and high overcast, which helps nobody. Generator B holding at 4.3 kW, fuel 341 L. Coil and drums arrive Wednesday if the wind drops and Thursday if it does not.",
    severity: 'notice',
    tags: ['logistics', 'supply'],
    hoursAgo: 226,
    filedBy: 'Ptarmigan',
    coords: null,
  },
  {
    stationCode: 'ULG-06',
    title: 'Lenticular stack over the saddle',
    body: 'Standing lenticulars lined up east of the saddle from 0900, the lowest about 4,200 m. Surface wind 11 m/s from the west, gusting 19. Pressure falling 1.4 hPa an hour. The valley net forecasts a front by evening. It arrived at 1830, ten minutes after the forecast, which is a record for that net.',
    severity: 'routine',
    tags: ['storm'],
    hoursAgo: 214,
    filedBy: 'Dunlin-1',
    coords: near('ULG-06', 0.0015, -0.0033),
  },
  {
    stationCode: 'RVN-01',
    title: 'Flight down, coil fitted, Generator A running',
    body: 'Flight on the ground at 1420. 600 L in twelve drums, one coil, one plug set, and a box of oranges nobody ordered. Coil fitted at 1610 and Generator A started on the first pull. The third-pull record stands at eleven mornings. Generator B back to standby; A carrying 4.0 kW.',
    severity: 'routine',
    tags: ['power', 'supply'],
    hoursAgo: 200,
    filedBy: 'Ingram',
    coords: near('RVN-01', 0.0006, -0.0021),
  },
  {
    stationCode: 'BRD-08',
    title: 'Swarm over, background returned',
    body: 'Event rate fell to 2 an hour by 0600 and under 1 an hour by 1400. Total for the sequence: 312 located events, largest M 2.6 at 2031. No damage to the hut or the instrument. The regional desk closed reference 4471 and classed the sequence as a swarm, not a precursor. We note their confidence and keep the boots by the bed.',
    severity: 'routine',
    tags: ['seismic'],
    hoursAgo: 190,
    filedBy: 'Brindle',
    coords: null,
  },
  {
    stationCode: 'KRN-07',
    title: 'First lead in the shore-fast ice',
    body: "A crack 30 m long opened parallel to the skerry's east shore at 1000 and closed again by 1800. Width peaked at 15 cm. Ice at the auger hole by the boat slip: 61 cm. Tide range 1.4 m. Ice inspection moved to every second day, same hole.",
    severity: 'routine',
    tags: ['ice'],
    hoursAgo: 176,
    filedBy: 'Wren-6',
    coords: near('KRN-07', 0.0009, 0.0038),
  },
  {
    stationCode: 'OST-09',
    title: 'Gauge datum re-levelled',
    body: 'Levelled the gauge to the brass bench mark on the quay wall. Offset 4 mm, inside tolerance and left uncorrected. The bench mark carries a dent from a boat hook that predates everyone here. Observed against predicted tide: residual under 6 cm for the week.',
    severity: 'routine',
    tags: ['instrument', 'survey'],
    hoursAgo: 162,
    filedBy: 'Mace-2',
    coords: null,
  },
  {
    stationCode: 'HLV-02',
    title: 'Spare anemometer cups missed the flight',
    body: 'Checked the freight list twice; the cups are not on it. The store says they were packed. The flight says the box was bumped for fuel. Next slot in nine days. Main anemometer stays taped and flagged suspect. The backup vane reads to 25 m/s and forecast gusts this week are in the low twenties, so no gap is expected unless the forecast is wrong. Station remains degraded on instrument grounds.',
    severity: 'notice',
    tags: ['supply', 'instrument'],
    hoursAgo: 150,
    filedBy: 'Halloran',
    coords: null,
  },
  {
    stationCode: 'KRN-07',
    title: 'Ice thickness down to 38 cm',
    body: 'Auger at the slip: 38 cm, down from 61 in seven days. Surface grey and candled, cores falling apart in the hand. Two more leads, the widest 40 cm, running across the approach to the landing. Sledge traffic confined to the marked track. Boat prepared and launched dry at 1500 as a rehearsal.',
    severity: 'notice',
    tags: ['ice', 'logistics'],
    hoursAgo: 138,
    filedBy: 'Wren-6',
    coords: near('KRN-07', 0.0011, 0.0046),
  },
  {
    stationCode: 'OST-09',
    title: 'Drift ice on the gauge approach',
    body: 'Pans of ice 2 to 5 m across are drifting past the quay at 1 knot on the ebb. One struck the gauge housing at 0545; the trace shows a 9 cm spike with no tide behind it. Checked the housing at low water: dented, not holed. Data from 0540 to 0600 flagged. Wind northwest 6 m/s.',
    severity: 'notice',
    tags: ['ice', 'instrument'],
    hoursAgo: 128,
    filedBy: 'Mace-2',
    coords: near('OST-09', -0.0002, 0.0014),
  },
  {
    stationCode: 'GLM-12',
    title: 'Gusts to 97 km/h on the ridge',
    body: 'Anemometer peak 27 m/s at 1520, which is 97 km/h. Hut holding. Two of the four cables singing, the third humming, the fourth silent, and I am watching the fourth. The door opens only on the lee side. Relay forwarded 61 messages in the last hour. Outdoor rounds suspended until gusts fall below 20 m/s.',
    severity: 'urgent',
    tags: ['storm', 'comms'],
    hoursAgo: 120,
    filedBy: 'Lomax',
    coords: near('GLM-12', 0.0004, -0.0007),
  },
  {
    stationCode: 'HLV-02',
    title: 'Teague-3 overdue from the snow pillow round',
    body: 'Teague-3 left the hut at 1605 for the snow pillow, 200 m uphill on the marked line, a 20 minute round. Not back at 1705. Whiteout, visibility under 10 m, wind 21 m/s. Filed at 1712. Halloran is on the rope line from the door and has gone out 60 m on the tether, calling. Generator kept running as a sound marker.',
    severity: 'critical',
    tags: ['storm', 'medical'],
    hoursAgo: 108,
    filedBy: 'Halloran',
    coords: near('HLV-02', 0.0012, 0.0016),
  },
  {
    stationCode: 'HLV-02',
    title: 'Teague-3 back at the hut',
    body: 'Teague-3 walked in at 1733 by following the rain gauge line, then the fence, then the sound of the generator. 88 minutes out. Fingers and two toes cold-damaged but not frozen: white, then red. Warmed in water at 38 C. No blistering by 2100. The rope line from hut to snow pillow has been added to the job list, which the handbook had already required. Teague-3 is excused the round for two days.',
    severity: 'routine',
    tags: ['medical', 'storm'],
    hoursAgo: 106,
    filedBy: 'Halloran',
    coords: null,
  },
  {
    stationCode: 'ULG-06',
    title: '0600 scheduled contact not received',
    body: 'Net control log, filed from Ravn Holm. ULG-06 did not answer the 0600 UTC call: three attempts on the primary and two on the alternate, ending 0612. No carrier heard. Their last traffic was yesterday at 1800, routine, nothing to suggest trouble. Try again at 1200.',
    severity: 'notice',
    tags: ['comms'],
    hoursAgo: 101,
    filedBy: 'Ingram',
    coords: null,
  },
  {
    stationCode: 'ULG-06',
    title: 'Second scheduled contact missed',
    body: 'The 1200 UTC call went unanswered on every frequency, to 1222. The valley net heard nothing either. Three crew on station, 41 days of rations at handover, no known injury or illness as of yesterday. Regional rescue liaison informed at 1230 and gave reference 2290. Next attempt at 1800, then hourly.',
    severity: 'urgent',
    tags: ['comms'],
    hoursAgo: 95,
    filedBy: 'Ingram',
    coords: null,
  },
  {
    stationCode: 'ULG-06',
    title: 'Contact restored; panel was buried, nobody hurt',
    body: 'On the air again at 1746 UTC. A drift off the roof ridge buried the solar panel after a snow squall and the battery fell below the transmitter cut-off at 0340. Nobody noticed until the morning log, by which time the radio was off and there was nothing to notice with. Panel cleared by 1300 and needed four hours of sun before the transmitter would start. We did try the handheld, on the wrong channel. Reference 2290 closed.',
    severity: 'routine',
    tags: ['comms', 'power'],
    hoursAgo: 90,
    filedBy: 'Dunlin-1',
    coords: near('ULG-06', 0.0006, 0.0011),
  },
  {
    stationCode: 'KRN-07',
    title: 'Open water 400 m off the skerry',
    body: 'Ice edge retreated to 400 m off the east shore by 0930 and is moving out on the ebb. The landing is now open water; access by boat only. Pack ice in sight to the north-east, loose pans 10 to 30 m across. Ostby reports the same on their side. Boat petrol 52 L, enough for four crossings. Top-up needed before the next supply day.',
    severity: 'urgent',
    tags: ['ice', 'logistics'],
    hoursAgo: 86,
    filedBy: 'Wren-6',
    coords: near('KRN-07', 0.0014, 0.0061),
  },
  {
    stationCode: 'TLV-04',
    title: 'Rime on the mast and upper guys',
    body: 'Rime 6 mm on the upper guys at the 0900 round, 3 mm on the mast. Wind 9 m/s from the east, -4 C, fog. Main feeder SWR 1.3, which is fine. Knocking it off the lower guys each round. The upper guys are out of reach without climbing, and the handbook forbids climbing in these conditions.',
    severity: 'notice',
    tags: ['ice', 'comms'],
    hoursAgo: 80,
    filedBy: 'Kestrel-9',
    coords: near('TLV-04', 0.0007, -0.0012),
  },
  {
    stationCode: 'SKR-11',
    title: 'Aurora, 2310 to 0140',
    body: 'Green arc to the north at 2310, folding into curtains overhead by 2350. The all-sky camera logged 300 frames. Magnetometer K index 5 at the peak. HF link to the relay degraded by one S-unit. The forms have no line for this, so it goes under remarks.',
    severity: 'routine',
    tags: ['aurora', 'instrument'],
    hoursAgo: 76,
    filedBy: 'Orsk',
    coords: near('SKR-11', 0.0005, 0.0009),
  },
  {
    stationCode: 'TLV-04',
    title: 'Ice loading on the mast: 22 mm',
    body: 'Rime now 22 mm on the upper guys and 14 mm on the mast sections above 20 m. North-east guy tension reads 15 percent above nominal. Feeder SWR 3.1 with 9 W reflected, so throughput is down to 35 percent and we are relaying for Ostby and Kerrin only. Freezing fog for the next two hours; nothing will come off until it lifts. Wind 7 m/s E, -6 C, humidity 98 percent.',
    severity: 'urgent',
    tags: ['ice', 'comms'],
    hoursAgo: 72,
    filedBy: 'Kestrel-9',
    coords: near('TLV-04', 0.0005, -0.0009),
  },
  {
    stationCode: 'RVN-01',
    title: '0500 sounding reached 31.2 km',
    body: 'Balloon burst at 31.2 km after 104 minutes. Sonde data complete to 27 km, patchy above. Tropopause at 8.9 km, -58 C. The parachute turned up on the roof of the fuel store, where it was not expected. The sonde itself is not recoverable.',
    severity: 'routine',
    tags: ['instrument', 'survey'],
    hoursAgo: 70,
    filedBy: 'Ptarmigan',
    coords: near('RVN-01', 0.0007, 0.0012),
  },
  {
    stationCode: 'KRN-07',
    title: 'Ice parted between the landing and the skerry',
    body: 'At 1340 the shore-fast ice split along the approach track. Wren-6 on the skerry side; Mace-2, visiting from Ostby with the instrument sledge, on the far side. Gap 2 m and widening, sledge 180 m from the open edge. Mace-2 was back in the boat by 1352 and unhurt. Eleven crates still on the ice. Landing closed until further notice.',
    severity: 'critical',
    tags: ['ice', 'logistics'],
    hoursAgo: 66,
    filedBy: 'Wren-6',
    coords: near('KRN-07', 0.0012, 0.0058),
  },
  {
    stationCode: 'KRN-07',
    title: 'Sledge and crates recovered',
    body: 'Eleven crates out, eleven counted back. One took water; the loggers inside are dry in their cases. Boat crossing was 12 minutes each way in a 0.6 m swell. One glove lost to the sea. Ice on the approach gone by 1800. All traffic by boat until the supply vessel, due Saturday.',
    severity: 'notice',
    tags: ['ice', 'logistics'],
    hoursAgo: 64,
    filedBy: 'Mace-2',
    coords: near('KRN-07', 0.0006, 0.0033),
  },
  {
    stationCode: 'VLD-13',
    title: 'Gale warning, array cleared',
    body: 'Warning from the valley net: northwest gale from 2100, snow to 40 cm, drifting. Bank at 12.5 V at 1530 with six hours of sun left. Cleared the array, lashed the hut shutters and moved the spare fuel can into the vault. Logger at 68 percent disk. Next call 2000.',
    severity: 'notice',
    tags: ['storm', 'power'],
    hoursAgo: 60,
    filedBy: 'Sable-4',
    coords: near('VLD-13', 0.0003, -0.0006),
  },
  {
    stationCode: 'HLV-02',
    title: 'Pressure trace ahead of the gale',
    body: 'Barometer 984 hPa at 1600, falling 2.1 hPa an hour for six hours. The taped anemometer reads 16 m/s, gusting 23, and cannot be trusted past 25. Precipitation gauge heater on. Snow at the hut door 12 cm. Both crew inside after 1900 and the rope line checked end to end.',
    severity: 'routine',
    tags: ['storm', 'instrument'],
    hoursAgo: 56,
    filedBy: 'Teague-3',
    coords: null,
  },
  {
    stationCode: 'VLD-13',
    title: 'Array buried, bank at 11.4 V',
    body: 'The gale arrived at 2040. A drift covered the array at about 0100 and the bank has fallen 0.1 V an hour since. Seismometer and logger draw 38 W; transmitting adds 55 W. Load shed: vault heater off, hut lights off, transmit limited to the hourly call. Cannot reach the array in this wind.',
    severity: 'urgent',
    tags: ['power', 'storm'],
    hoursAgo: 46,
    filedBy: 'Sable-4',
    coords: near('VLD-13', 0.0003, -0.0008),
  },
  {
    stationCode: 'VLD-13',
    title: 'Bank at 10.9 V, seismometer shut down',
    body: 'Bank 10.9 V at 0930. Seismometer and logger powered down to keep the radio alive; the vault is off the record from this entry. Transmit now only on the handheld at 0800 and 2000, 2 W. Crew of two, dry, fed, with six days of food and a stove that burns the wood we carried up. Array still buried. We will dig when the wind allows.',
    severity: 'critical',
    tags: ['power', 'seismic'],
    hoursAgo: 43,
    filedBy: 'Sable-4',
    coords: null,
  },
  {
    stationCode: 'OST-09',
    title: 'Stores count before the supply vessel',
    body: 'Stores at 1000. Boat petrol 38 L. Stove oil 140 L. Flour 9 kg. Tea 2 kg. D-cell batteries 14. Spare gauge float 1. Order sent for petrol 120 L, stove oil 200 L, batteries 40 and a pane for the north window, which has a crack that arrived with the drift ice and stayed.',
    severity: 'routine',
    tags: ['supply', 'logistics'],
    hoursAgo: 44,
    filedBy: 'Mace-2',
    coords: null,
  },
  {
    stationCode: 'TLV-04',
    title: 'Fog lifted; most of the rime gone',
    body: 'Fog lifted at 0540 and the sun took most of the rime off the mast by 1100. Nine millimetres left on the upper guys, knocked down with a hooked pole. SWR 1.9, which is better than 3.1 and worse than 1.3. Throughput back to 80 percent. Still relaying for Ostby and Kerrin only until the SWR falls.',
    severity: 'notice',
    tags: ['ice', 'comms'],
    hoursAgo: 40,
    filedBy: 'Kestrel-9',
    coords: near('TLV-04', 0.0006, -0.0008),
  },
  {
    stationCode: 'GLM-12',
    title: 'Valley repeater down; forwarding for two stations',
    body: 'With the valley repeater off, this relay is forwarding Halvard and Velden traffic. Held 27 messages. Each one is kept until forwarded and kept again until its receipt comes back; two needed a third attempt. Nothing deleted on a guess. Queue empty at 1615.',
    severity: 'routine',
    tags: ['comms'],
    hoursAgo: 38,
    filedBy: 'Lomax',
    coords: null,
  },
  {
    stationCode: 'ULG-06',
    title: 'Hygrometer element replaced',
    body: 'Old element read 71 percent when the wet bulb said 58. New element agrees within 2 percent. At 3,100 m the wet bulb freezes before it reads, so the comparison was against the electronic unit. Old element kept in its sleeve and labelled, in case anyone wants to be disappointed in it.',
    severity: 'routine',
    tags: ['instrument', 'maintenance'],
    hoursAgo: 36,
    filedBy: 'Dunlin-1',
    coords: null,
  },
  {
    stationCode: 'VLD-13',
    title: 'Velden silent for eight hours',
    body: 'Filed from Halvard on the station\'s behalf. Last heard: the 2000 handheld call, weak but readable. The 0800, 1200 and 1600 calls were not heard on the handheld channel or the set. Two crew, food for about six days, bank at 10.9 V when they shut down. Ground access 11 km over unmarked drift, closed by the weather hold. Regional liaison informed, reference 3318.',
    severity: 'urgent',
    tags: ['comms', 'power'],
    hoursAgo: 26,
    filedBy: 'Halloran',
    coords: near('VLD-13', 0.0004, 0.0004),
  },
  {
    stationCode: 'BRD-08',
    title: 'Teleseism recorded; Velden not recording',
    body: 'M 5.9 from the south Pacific at 0417, clean on all components, first arrival within 2 s of the predicted time. The regional desk asked whether Velden is recording. It is not. Bredon noise floor unchanged. Desk duty suits Brindle in the sense that it is a chair.',
    severity: 'routine',
    tags: ['seismic', 'handover'],
    hoursAgo: 24,
    filedBy: 'Brindle',
    coords: null,
  },
  {
    stationCode: 'RVN-01',
    title: 'HF gone on every band, 0310 to 0750',
    body: 'Polar cap absorption. All bands dead from 0310, first signs at 0250. Kept the written log through the gap: 14 messages held in order with the time each was composed. Link back at 0751. Replayed all 14 in sequence and asked for a receipt number on each. Twelve came back at once, two after a repeat.',
    severity: 'notice',
    tags: ['aurora', 'comms'],
    hoursAgo: 22,
    filedBy: 'Ingram',
    coords: null,
  },
  {
    stationCode: 'SKR-11',
    title: 'Terminus walked with the GPS',
    body: 'Walked the front at 1000. Retreat since the last walk: 11 m at the centre, 4 m at the north margin, 18 m at the south where the ice is thin and dirty. Calving face 6 m high. A block the size of a car is sitting on what was a moraine path yesterday. Path re-marked 20 m to the east.',
    severity: 'routine',
    tags: ['ice', 'survey'],
    hoursAgo: 19,
    filedBy: 'Orsk',
    coords: near('SKR-11', -0.0044, -0.0102),
  },
  {
    stationCode: 'KRN-07',
    title: 'No ice within 3 km; ice log closed',
    body: 'No ice in sight to the horizon at 1500. The ice log is closed; its first entry is 176 hours ago. Boat crossings at 0830 and 1630 when the swell is under 1 m, otherwise none. The Ostby gauge agrees with our sea level readings to within 3 cm.',
    severity: 'routine',
    tags: ['ice'],
    hoursAgo: 16,
    filedBy: 'Wren-6',
    coords: null,
  },
  {
    stationCode: 'HLV-02',
    title: 'Hold expected to lift; Velden party being arranged',
    body: 'Forecast: wind under 12 m/s from 0400, ceiling above 200 m by 0700. A helicopter has been asked for first light; ground party of two stands by as the fallback, carrying the sledge, the stove and the spare handheld. Halvard stays manned by whoever does not go. The rope line from door to gauge is intact.',
    severity: 'urgent',
    tags: ['storm', 'logistics'],
    hoursAgo: 12,
    filedBy: 'Halloran',
    coords: null,
  },
  {
    stationCode: 'TLV-04',
    title: 'Water in the feeder connector',
    body: 'Opened the N-connector at the antenna base: water inside, a green bloom on the centre pin. Cleaned the pin, dried the body, wrapped it in self-amalgamating tape. SWR 1.4 in still air. This is not a proper repair and is logged as a temporary one. Spare connector on the next flight, nine days if the box is not bumped.',
    severity: 'notice',
    tags: ['comms', 'maintenance'],
    hoursAgo: 9,
    filedBy: 'Kestrel-9',
    coords: near('TLV-04', 0.0003, -0.0005),
  },
  {
    stationCode: 'GLM-12',
    title: 'Wind down to 12 m/s, rounds resumed',
    body: 'Gusts below 15 m/s since 1100. Walked all four cable anchors: the silent one was the one with a loose shackle, now tightened. Mast clear of ice. Door opens on both sides again. Relay traffic normal, 44 messages in the last hour.',
    severity: 'notice',
    tags: ['storm', 'maintenance'],
    hoursAgo: 5,
    filedBy: 'Lomax',
    coords: near('GLM-12', -0.0003, 0.0006),
  },
  {
    stationCode: 'ULG-06',
    title: 'Panel and vane cleared, angle set for the season',
    body: 'Daily check: snow off the solar panel and the wind vane. Panel angle set to 38 degrees for the winter sun. Battery 13.1 V at 1100 and charging. The valley net confirms it heard our 1000 call at signal strength 5, which is more than we expected.',
    severity: 'routine',
    tags: ['power', 'maintenance'],
    hoursAgo: 3.4,
    filedBy: 'Dunlin-1',
    coords: near('ULG-06', 0.0004, 0.0009),
  },
  {
    stationCode: 'RVN-01',
    title: 'Polar bear 120 m from the hut',
    body: 'Adult bear seen from the roof at 1204 moving toward the fuel store. Flare fired at 60 m. Bear turned and walked off to the north along the shoreline, unhurried. Crew inside with the door pinned. Bear watch kept from the roof for 40 minutes. Nothing damaged. Drums checked against the list: all present.',
    severity: 'urgent',
    tags: ['wildlife'],
    hoursAgo: 1.6,
    filedBy: 'Ptarmigan',
    coords: near('RVN-01', -0.0009, 0.0052),
  },
  {
    stationCode: 'OST-09',
    title: 'Gauge trace normal, no spikes since Tuesday',
    body: 'Trace clean through both tides. Predicted against observed residual 4 cm. Drift ice gone from the approach. Housing dent noted, unchanged.',
    severity: 'routine',
    tags: ['instrument'],
    hoursAgo: 0.85,
    filedBy: 'Mace-2',
    coords: near('OST-09', -0.0003, 0.0008),
  },
  {
    stationCode: 'SKR-11',
    title: 'Meltwater channel across the line B track',
    body: 'A channel 40 cm wide and 25 cm deep opened across the line B track overnight, running fast. Crossed on the planks at 1040. Planks now frozen to the bank at one end. Flagged the crossing and moved the stake run to the upper route until the flow drops.',
    severity: 'notice',
    tags: ['ice', 'survey'],
    hoursAgo: 0.6,
    filedBy: 'Orsk',
    coords: near('SKR-11', 0.0039, 0.0088),
  },
  {
    stationCode: 'KRN-07',
    title: 'Barograph trace changed at 1030',
    body: 'Pressure 1004 hPa and falling slowly. Pen nib fine. The drum is four minutes fast again, as promised.',
    severity: 'routine',
    tags: ['instrument'],
    hoursAgo: 0.35,
    filedBy: 'Wren-6',
    coords: null,
  },
  {
    stationCode: 'TLV-04',
    title: 'Link dropped for 11 minutes in gusts',
    body: 'Feeder SWR jumped to 2.4 in gusts over 14 m/s and the link to Tulvik dropped from 1012 to 1023. Recovered by itself. Connector tape looks intact from the ground. Traffic held in the written log and replayed in order, 9 messages, receipts confirmed on each.',
    severity: 'urgent',
    tags: ['comms', 'maintenance'],
    hoursAgo: 0.2,
    filedBy: 'Kestrel-9',
    coords: near('TLV-04', 0.0002, -0.0004),
  },
]

/**
 * Events the wire generator can file at any station. {station}, {code} and {n} are
 * substituted by the store; {n} is used only where any small positive integer reads naturally.
 * `kinds` narrows a template to station kinds where it makes physical sense.
 */
export const WIRE_TEMPLATES: WireTemplate[] = [
  // routine
  {
    title: 'Morning round complete',
    body: 'All instruments at {code} read and logged. Nothing to report beyond the ordinary: the stove took twenty minutes to draw and the thermometer screen had to be chipped free of frost.',
    severity: 'routine',
    tags: ['instrument'],
  },
  {
    title: 'Ledger pages counted',
    body: 'Counted the pages left in the station ledger. Pages remaining: {n}. At the current rate that is enough to reach the handover with some to spare. A spare ledger is on the next order anyway, because paper is cheaper than the alternative.',
    severity: 'routine',
    tags: ['logistics', 'maintenance'],
  },
  {
    title: 'Stove swept, draw improved',
    body: 'Swept the stove pipe at {station}. Soot bucket full, damper moving freely again. The hut is now warm in the wrong corner, which is an improvement on cold in all of them.',
    severity: 'routine',
    tags: ['maintenance'],
  },
  {
    title: 'Faint aurora, northern sky',
    body: 'A pale green arc low in the north from 2215, gone by midnight. Magnetometer quiet and HF unaffected. Logged because the log has a column for it and somebody checks the column.',
    severity: 'routine',
    tags: ['aurora'],
  },
  {
    title: 'Generator serviced, 500 hours',
    body: 'Oil and filter changed on the main generator at {code}. Old oil drained to the marked drum. Fifteen minutes under load afterwards: no leaks, no noises beyond the usual ones, exhaust colour normal.',
    severity: 'routine',
    tags: ['power', 'maintenance'],
  },
  {
    title: 'Rations count',
    body: 'Counted the dry store against the list. Flour, rice, oats, tea and tinned fish all within a day of the expected figure. Coffee is the exception and is now discussed in the present tense.',
    severity: 'routine',
    tags: ['supply'],
  },
  {
    title: 'Swell from the north-west, boat stays on the slip',
    body: 'Swell 1.2 m from the north-west at a 9 second period. Sea temperature 3.1 C at the intake. Spray has glazed the slip rail; chipped and salted. Boat stays where it is until the period drops under 7 seconds.',
    severity: 'routine',
    tags: ['logistics'],
    kinds: ['coastal'],
  },
  {
    title: 'Ablation stakes read',
    body: 'Stake line read at 1100 on dry ice with a thin film of water. Four of five stakes down by 0.3 to 0.5 m since the last reading. The fifth is leaning and was reset upright with the drill.',
    severity: 'routine',
    tags: ['ice', 'survey'],
    kinds: ['glacier'],
  },
  {
    title: 'Vault temperature steady',
    body: 'Vault temperature steady to within 0.05 C over the week. Seismometer mass centred. Background noise in the microseism band ordinary for the season. Door seal checked and left alone.',
    severity: 'routine',
    tags: ['seismic', 'instrument'],
    kinds: ['seismic'],
  },
  {
    title: 'Sounding complete',
    body: 'Balloon released on time and the radiosonde reported on every channel until burst above 28 km after 97 minutes. Data complete to 25 km and filed. Parachute found in the snow 300 m downwind, sonde not recovered.',
    severity: 'routine',
    tags: ['instrument', 'survey'],
    kinds: ['weather'],
  },
  {
    title: 'Evening window traffic',
    body: 'Messages forwarded in the evening window: {n}. None held, none repeated, one garbled and requested again. Receipts returned on all of them before the window closed.',
    severity: 'routine',
    tags: ['comms'],
    kinds: ['radio-relay'],
  },
  {
    title: 'Station clock checked against the time signal',
    body: 'Station clock 1.4 s slow against the time signal and corrected. The mechanical clock in the hut is 11 minutes slow and has been left as it is, out of respect.',
    severity: 'routine',
    tags: ['instrument'],
  },
  {
    title: 'Snow depth at the reference stake',
    body: 'Snow depth at the reference stake 34 cm, up 2 cm on Monday. Density sample 280 kg per cubic metre. Core tube cleaned and oiled. The stake itself has a small lean that predates the current crew.',
    severity: 'routine',
    tags: ['survey'],
  },
  {
    title: 'Arctic fox at the lamp circle',
    body: 'An arctic fox sat at the edge of the lamp circle for about forty minutes and left when the kettle whistled. Nothing taken. Tracks photographed, direction of travel noted.',
    severity: 'routine',
    tags: ['wildlife'],
  },
  {
    title: 'Handover notes updated',
    body: 'Updated the handover notes for {code}. Spare fuses: tin, left of the door. Sticking drawer: the second one. Radio channel with a hum: the third, in rain. Nothing else the next crew cannot find on the first day.',
    severity: 'routine',
    tags: ['handover'],
  },
  {
    title: 'Supply flight confirmed',
    body: 'Flight to {station} confirmed for the day after tomorrow, weather permitting, which is a large qualification. Crates on the manifest: {n}, mostly fuel and flour. The operator would not commit to an hour.',
    severity: 'routine',
    tags: ['logistics', 'supply'],
  },
  // notice
  {
    title: 'Anemometer bearing noisy',
    body: 'The main anemometer has a dry rasp at low speeds, audible from the door. Readings agree with the backup within 4 percent, so it stays in service. Bearing oil requested; the present tin was opened by a previous crew and has thickened.',
    severity: 'notice',
    tags: ['instrument', 'maintenance'],
    kinds: ['weather', 'coastal', 'glacier'],
  },
  {
    title: 'Pressure down 6 hPa in three hours',
    body: 'Barometer at {code} fell 6 hPa in three hours and is still falling. Cloud lowering from the west. Shutters fitted and outdoor rounds brought forward ahead of the weather.',
    severity: 'notice',
    tags: ['storm'],
  },
  {
    title: 'Supply flight delayed a day',
    body: 'The flight to {station} has moved back one day. The operator cites crosswind at the departure strip. Here it is calm and clear, which does not help. Stores are adequate to the new date.',
    severity: 'notice',
    tags: ['logistics', 'supply'],
  },
  {
    title: 'Generator slow to start',
    body: 'The main generator took four attempts this morning, where two is usual. Choke and plug checked, both fine. Fuel filter bowl shows a little water; drained. Will watch it over the next three starts.',
    severity: 'notice',
    tags: ['power', 'maintenance'],
  },
  {
    title: 'Fuel stock at twenty-two days',
    body: 'Fuel at {code} now reads 22 days at the current burn. Above the reserve line, below the comfortable one. Second heater to be used only after dark. Next delivery is on the flight schedule but not on a date.',
    severity: 'notice',
    tags: ['power', 'supply'],
  },
  {
    title: 'Sea ice moving on the ebb',
    body: 'Loose pans of ice 5 to 20 m across moving past the station on the ebb at about 1 knot. Shore-fast edge intact for now. Boat stays on the slip; ice inspection moved to every watch.',
    severity: 'notice',
    tags: ['ice', 'logistics'],
    kinds: ['coastal', 'glacier'],
  },
  {
    title: 'Mast guy slack on the north side',
    body: 'The north guy has slackened by about 20 mm after two days of wind. Tension restored with the turnbuckle and locked. Reflected power unchanged at 0.5 W. Anchor checked for movement and found in place.',
    severity: 'notice',
    tags: ['comms', 'maintenance'],
    kinds: ['radio-relay'],
  },
  {
    title: 'Microseism noise up 12 dB',
    body: 'Noise in the 0.1 to 0.3 Hz band has risen 12 dB since the sea got up to the south. Expected at this time of year and not a fault. Event detection thresholds raised for the duration so the logger does not file the ocean.',
    severity: 'notice',
    tags: ['seismic', 'instrument'],
    kinds: ['seismic'],
  },
  {
    title: 'Long-distance skip clutter on the net',
    body: 'Stations from two other regions coming in over the net at S7 and stepping on our traffic. Moved scheduled calls to the alternate channel. Skip lasted most of the evening and faded around 0100.',
    severity: 'notice',
    tags: ['comms'],
  },
  {
    title: 'Drifting snow at the door',
    body: 'Snow drifting to 60 cm at the main door, wind 11 m/s and steady. Cleared twice today. Emergency exit checked and clear. Rounds continue on the rope line.',
    severity: 'notice',
    tags: ['storm', 'maintenance'],
  },
  {
    title: 'Sonde signal lost early',
    body: 'Radiosonde signal lost at 14 km, well short of the usual burst height. Receiver gain and antenna checked and sound. Probably a sonde fault. Second sonde prepared and launched on the next slot.',
    severity: 'notice',
    tags: ['instrument'],
    kinds: ['weather'],
  },
  {
    title: 'Wind vane sticking',
    body: 'The wind vane hangs for a few seconds before it swings, most often below 2 m/s. Direction values are good once it moves. Bearing cleaned with solvent; a proper check when the weather allows a climb.',
    severity: 'notice',
    tags: ['instrument', 'maintenance'],
  },
  {
    title: 'Crew member with a cold',
    body: 'One of the crew at {station} has a cold and a low fever, 37.8 C. Resting and drinking. Duties shared among the rest. If it climbs above 38.5 C or reaches the chest, a radio consultation is booked.',
    severity: 'notice',
    tags: ['medical'],
  },
  {
    title: 'Datalogger clock stepped',
    body: 'The datalogger clock stepped forward 2 s at 0411 after a GPS resync. Data either side flagged. The step was a correction, not a fault, but the trace has a gap in it that somebody will ask about.',
    severity: 'notice',
    tags: ['instrument'],
  },
  {
    title: 'Meltwater across the tracks',
    body: 'Meltwater channels cutting across the stake tracks, the widest 50 cm and fast. Crossing on planks. Two stakes out of reach until the flow drops. Route changed to the upper line.',
    severity: 'notice',
    tags: ['ice', 'survey'],
    kinds: ['glacier'],
  },
  // urgent
  {
    title: 'Wind 25 m/s, rounds suspended',
    body: 'Gusts to 25 m/s at {code}. Outdoor rounds suspended. Instruments read from inside where possible and estimated where not; the estimates are flagged. Hut holding. Door on the lee side only.',
    severity: 'urgent',
    tags: ['storm'],
  },
  {
    title: 'Battery bank below half',
    body: 'Battery bank at {station} reads 49 percent at dawn and fell another 6 percent by midday. Panel output poor under cloud. Load shed in stages: lights, then heater, then non-essential logging. Generator started and on charge.',
    severity: 'urgent',
    tags: ['power'],
  },
  {
    title: 'Feeder reflecting heavily',
    body: 'Reflected power at the feeder has risen to 11 W on the main channel. Throughput down by two thirds. Traffic moved to the reserve antenna, which covers two of three neighbours. Connector and cable check needs a dry hour and a pair of hands.',
    severity: 'urgent',
    tags: ['comms', 'maintenance'],
    kinds: ['radio-relay'],
  },
  {
    title: 'Polar bear near the hut',
    body: 'A bear was sighted at 150 m from the station, moving toward the store. Crew inside and door pinned. Flare held ready and used at 50 m; the bear turned away. Watch kept from the roof for the next hour.',
    severity: 'urgent',
    tags: ['wildlife'],
  },
  {
    title: 'Event rate rising',
    body: 'Local events in the last hour: {n}, against a normal rate of about one a day. Largest M 2.1. Located within 10 km of the station. Mass re-centred. Boots by the bed and the regional desk called; awaiting their reference number.',
    severity: 'urgent',
    tags: ['seismic', 'comms'],
    kinds: ['seismic'],
  },
  {
    title: 'Scheduled contact missed',
    body: 'No answer on the scheduled call from {code}. Primary and alternate channels tried for 20 minutes. Last traffic was routine. Net control will try again on the hour and every hour after.',
    severity: 'urgent',
    tags: ['comms'],
  },
  {
    title: 'Fuel weeping at the day tank',
    body: 'Found a slow weep at the day tank fitting at {station}, about a cupful an hour. Tank valved off and the drip tray emptied into a marked drum. Generators on the main store by hose. Clamp and sealant tried; result to be confirmed.',
    severity: 'urgent',
    tags: ['power', 'maintenance'],
  },
  {
    title: 'Frostbite, second crew member',
    body: 'Second case at {station} in a week. Two fingers white to the second joint after a repair outside. Re-warmed in water at 38 C, pain and swelling on return of colour. Radio consultation requested; outdoor work limited to pairs and twenty minutes.',
    severity: 'urgent',
    tags: ['medical'],
  },
  {
    title: 'Crack across the landing',
    body: 'A crack 25 cm wide opened across the landing ice between the shore and the station. Two crew on the far side at the time, brought back by boat. Landing closed and marked with flags. All traffic by boat.',
    severity: 'urgent',
    tags: ['ice', 'logistics'],
    kinds: ['coastal', 'glacier'],
  },
  // critical
  {
    title: 'Carbon monoxide alarm in the hut',
    body: 'Alarm sounded in the sleeping room at {station} at 0340, reading 90 ppm. Crew woken and out of the hut, windows opened, stove out. Reading 10 ppm after 30 minutes. Flue found blocked by rime at the cap. Cleared; no one to sleep in the hut until a second check.',
    severity: 'critical',
    tags: ['power', 'medical'],
  },
  {
    title: 'Crew member overdue on a round',
    body: 'One of the crew at {code} left for an outdoor round 70 minutes ago and is not back. Whiteout, visibility under 15 m. Second crew on the rope line from the door, calling. Generator kept running as a sound marker.',
    severity: 'critical',
    tags: ['storm', 'medical'],
  },
  {
    title: 'Fire in the generator shed, put out',
    body: 'Fire in the generator shed at {station} at 1620. Extinguished with two dry-powder cylinders in under four minutes. Nobody hurt. Fuel drums are undamaged and were moved clear. Generators out of service; station on batteries and the small set.',
    severity: 'critical',
    tags: ['power', 'maintenance'],
  },
  {
    title: 'Medical evacuation requested',
    body: 'Evacuation requested from {station}. Crew member with severe abdominal pain, vomiting, guarding, fever 39.1 C. Doctor on the radio suspects appendix. Flight operator tasked; weather at the strip marginal. Patient on the bunk, fasting, nothing by mouth.',
    severity: 'critical',
    tags: ['medical', 'logistics'],
  },
  {
    title: 'No charge source, batteries only',
    body: 'Both generators and the array at {code} are out of service. Bank at 58 percent. All non-essential load removed; radio limited to scheduled calls. Estimated 20 hours of reserve at this draw. Repair under way and the regional liaison informed.',
    severity: 'critical',
    tags: ['power', 'comms'],
  },
]
